import type { Metadata } from "next";
import ReduxProvider from "../redux/store/Provider"; // Redux Provider 불러오기

import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // ✅ children을 받아야 함
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          <Header />
          <main className="container mx-auto p-4"> {/* ✅ Tailwind 적용 */}
            {children} {/* ✅ children을 렌더링해야 Tailwind 적용됨 */}
          </main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
